### ISSUE TITLE
Fix compilation for librsync >= 1.0.0

### ISSUE THREAD

**Issue by axelgenus** [sol1/rdiff-backup#2]
I'm the maintainer of rdiff-backup and librsync in Gentoo. I had to use the Fedora patch[1] to fix compilation for librsync >= 1.0.0. Can you please apply this to the next release?

[1] http://pkgs.fedoraproject.org/cgit/rpms/rdiff-backup.git/plain/rdiff-backup-1.2.8-librsync-1.0.0.patch

**Comment by anomaly256** [comment]
Hi Alessandro, thanks for submitting this.  By the way I've messaged you on Freenode, I think we both asked for proxy-maint on rdiff-backup at nearly the same time via different routes.  Happy to co-maintain, lets discuss further on Freenode when we're both active at the same time
