### ISSUE TITLE
Broken links to www.nongnu.org

### ISSUE THREAD

**Issue by zakora** [sol1/rdiff-backup#25]
In the README there are many links that point to the **www**.nongnu.org domain.
This domain appears to return 404 only:
```
~> curl -I http://www.nongnu.org/rdiff-backup/
HTTP/1.1 404 Not Found
(...)
```
But it works if we omit the www.
Is this a temporary issue with www.nongnu.org? I can submit a PR if URL should be changed to not use www.

**Comment by afoster** [comment]
Hey @zakora , thanks for reporting this. I think it was a temporary issue with their web server, it seems OK for me now.
