### ISSUE TITLE
githubpage / README looks really technical

### ISSUE THREAD

**Issue by gorn** [sol1/rdiff-backup#3]
Thanks for taking over the project. I do not know if you can tell yourself, thats why I fill in this issue. If the github repo is going to be the new frontpage for the project, than it must be improved radically. It is very technical now - could you instead replace it by something more like http://www.nongnu.org/rdiff-backup/index.html with links to faq, installation etc? Btw installation can be as easy as aptitude install rdiff-backup.

**Comment by davekempe** [comment]
Hi gorn. 
I have already started work on a new website. We will be moving to a github hosted front page that will include more useful information.
rdiff-backup is included in debian and ubuntu, so you can just install it with aptitude now. We are the new upstream and will be releasing new version to them as part of this process.

**Comment by afoster** [comment]
Agree that although we're working on a new website, the README in this repo needs to be modernised. I'll put my hand up for that.

**Comment by afoster** [comment]
Work on the new website continues, but given I've replaced the GitHub README, I'll close this.
