### ISSUE TITLE
OverflowError: group id is less than minimum

### ISSUE THREAD

**Issue by devano1701** [sol1/rdiff-backup#30]
Can someone explain what is happening here?

I am running rdiff-backup version 1.2.8 on the latest build of raspbian on a RPi.
I want to back up some personal folders on a Synology NAS to a HDD attached to the RPi.
Currently I am setting up the system, so this is the first back up. For two folders it works fine. But on my folder with photos I get this error message.

According to the log-file the exception is thrown somewhere in the middle of the action. It seems that the process first continues, but soon after the process is stopped.

I just don’t understand the error. Is something wrong with the source folder? 

This is the last part of the log-file (-v3):

Processing changed file Zeeland (22~28-08-2004)/PICT0053.JPG
Processing changed file Zeeland (22~28-08-2004)/Thumbs.db
Processing changed file Zwitserland (15~27-07-2013)
Processing changed file Zwitserland (15~27-07-2013)/@eaDir
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG/SYNOPHOTO_THUMB_B.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG/SYNOPHOTO_THUMB_M.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG/SYNOPHOTO_THUMB_PREVIEW.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG/SYNOPHOTException 'group id is less than minimum' raised of class '<type 'exceptions.OverflowError'>':
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 346, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 38, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 232, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rorpiter.py", line 281, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 529, in fast_process
    if self.patch_to_temp(mirror_rp, diff_rorp, tf):
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 559, in patch_to_temp
    rpath.copy_attribs(diff_rorp, new)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 180, in copy_attribs
    rpout.chown(*rpout.conn.user_group.map_rpath(rpin))
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 977, in chown
    else: os.chown(self.path, uid, gid)

O_THUMB_S.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG/SYNOPHOTO_THUMB_XL.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09231.JPG
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09231.JPG/SYNOPHOTO_THUMB_B.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09231.JPG/SYNOPHOTO_THUMB_M.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09231.JPG/SYNOPHOTO_THUMB_PREVIEW.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09231.JPG/SYNOPHOTO_THUMB_S.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09231.JPG/SYNOPHOTO_THUMB_XL.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09232.JPG
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09232.JPG/SYNOPHOTO_THUMB_B.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09232.JPG/SYNOPHOTO_THUMB_M.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09232.JPG/SYNOPHOTO_THUMB_PREVIEW.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09232.JPG/SYNOPHOTO_THUMB_S.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09232.JPG/SYNOPHOTO_THUMB_XL.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09233.JPG
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09233.JPG/SYNOPHOTO_THUMB_B.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09233.JPG/SYNOPHOTO_THUMB_M.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09233.JPG/SYNOPHOTO_THUMB_PREVIEW.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09233.JPG/SYNOPHOTO_THUMB_S.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09233.JPG/SYNOPHOTO_THUMB_XL.jpg
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09234.JPG
Processing changed file Zwitserland (15~27-07-2013)/@eaDir/DSC09234.JPG/SYNOPHOTO_THUMB_B.jpg
Traceback (most recent call last):
  File "/usr/bin/rdiff-backup", line 30, in <module>
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 304, in error_check_Main
    try: Main(arglist)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 324, in Main
    take_action(rps)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 280, in take_action
    elif action == "backup": Backup(rps[0], rps[1])
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/Main.py", line 346, in Backup
    backup.Mirror(rpin, rpout)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 38, in Mirror
    DestS.patch(dest_rpath, source_diffiter)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 232, in patch
    ITR(diff.index, diff)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rorpiter.py", line 281, in __call__
    last_branch.fast_process(*args)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 529, in fast_process
    if self.patch_to_temp(mirror_rp, diff_rorp, tf):
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/backup.py", line 559, in patch_to_temp
    rpath.copy_attribs(diff_rorp, new)
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 180, in copy_attribs
    rpout.chown(*rpout.conn.user_group.map_rpath(rpin))
  File "/usr/lib/python2.7/dist-packages/rdiff_backup/rpath.py", line 977, in chown
    else: os.chown(self.path, uid, gid)
OverflowError: group id is less than minimum

**Comment by ikus060** [comment]
Have you check the groupid for the given files:
- Zwitserland (15~27-07-2013)/.JPG/SYNOPHOTO_THUMB_B.jpg
- Zwitserland (15~27-07-2013)/.JPG/SYNOPHOTO_THUMB_S.jpg

Possible your groupid for these files are not in range. Looking at python code (https://bugs.python.org/review/15301/diff/7979/Modules/posixmodule.c) this may happen if you groupid is to big. I guess your permissions might be wrong.

Quick way to test is to execute `chown` to change the userid and groupid.

**Comment by devano1701** [comment]
Thanks for your reaction and suggestion.
I have looked at the permissions and I believe they are ok.

root@raspberrypi:/mnt/Synology_photo/Zwitserland (15~27-07-2013)/@eaDir/DSC09230.JPG# ls -al
total 636
drwxrwxrwx   2 root root   4096 May 18  2014 .
drwxrwxrwx 648 root root  24576 May 18  2014 ..
-rwxrwxrwx   1 root root  56680 May 18  2014 SYNOPHOTO_THUMB_B.jpg
-rwxrwxrwx   1 root root  41737 May 18  2014 SYNOPHOTO_THUMB_M.jpg
-rwxrwxrwx   1 root root  13558 Jun  7  2016 SYNOPHOTO_THUMB_PREVIEW.jpg
-rwxrwxrwx   1 root root   4678 May 18  2014 SYNOPHOTO_THUMB_S.jpg
-rwxrwxrwx   1 root root 488125 May 18  2014 SYNOPHOTO_THUMB_XL.jpg

The owner of the real photos is “nobody”. 

root@raspberrypi:/mnt/Synology_photo/Zwitserland (15~27-07-2013)# ls -al
total 1025624
drwxrwxrwx   3 nobody users     20480 May 18  2014 .
drwxrwxrwx 174 root   root      12288 Feb 12 23:17 ..
-rwxrwxrwx   1 nobody users    899265 Jul 15  2013 DSC09230.JPG
-rwxrwxrwx   1 nobody users    906424 Jul 15  2013 DSC09231.JPG

But that is also the case in earlier directories. And also in other folders which were back-upped without problems.  

So I still do not know what my problem is and how to solve it.
Do you have other suggestions?

**Comment by devano1701** [comment]
Problem is solved. You were right.
Some files in de cours directory were mounted with owner -2 (probably an issue in NFS). 
Reloading the files in the source directory solved the problem.
Thanks again for your advice.

**Comment by ikus060** [comment]
Great! I'm glad you solve the issue. I was out of ideas.
