### ISSUE TITLE
Current release status

### ISSUE THREAD

**Issue by Zitrax** [sol1/rdiff-backup#4]
This is really a question and not a bug report.

I see there is a release marked stable (1.2.8) and one unstable (1.3.3); both 7 years old. Should one still go for 1.2.8 vs 1.3.3 vs building from source on master ?

**Comment by anomaly256** [comment]
Hi Zitrax, Debian, Ubuntu, and Fedora appear to use 1.2.8, likely with their own security/stability patches on top while Gentoo currently only offers 1.3.3.  Master isn't too far ahead of 1.3.3, however I have not yet had time to review the changes introduced by the commits beyond 1.3.3.  I am in the process of setting up virtual machines for Linux, Windows, and BSD (the 64bit uid/gid bug addressed in master appears to be more pertinent to the BSDs) for testing and development to make sure the commits in master fix the issues they intend to, at which point we will probably release a 1.3.4 with Alessandro's librsync patch and backport to 1.2.x if necessary/relevant.  At this stage, I would say go with 1.2.8 if you want stable and are performing remote backups of distros with rdiff-backup installed from their package management systems, master if you use a BSD and encounter the 64bit uid/gid issue, or 1.3.3 if you know it has features/fixes you require.  Our aim will of course be to stabilize the 1.3.x version in the near future.

**Comment by Zitrax** [comment]
Thank you for the information. I will probably go with 1.2.8 at this point then.

Great to see that the project is getting some attention again. Good luck.

**Comment by mhsmith** [comment]
Is the above still the current plan, or have there been any developments in the last year?

**Comment by anomaly256** [comment]
Hi @mhsmith, still the current plan however I've been sidetracked in recent times.  We will be dedicating some time to this shortly, in the next couple weeks.
