### ISSUE TITLE
Python 3 port

### ISSUE THREAD

**Issue by int-ua** [sol1/rdiff-backup#46]
I understand that it's still left unmaintained but I'll just create this issue for anyone to track progress if you don't mind.

#40

**Comment by ericzolf** [comment]
Hi Serhiy, as you noticed, there is already a PR on-going for this topic. If you're interested in helping out, join the conversation on the rdiff-backup-users mailing list started by Otto, see https://lists.nongnu.org/archive/html/rdiff-backup-users/2019-07/msg00005.html

**Comment by afoster** [comment]
Existing PR is https://github.com/sol1/rdiff-backup/pull/40 - closing
